# go services. images pulled from ghcr (built by ci). api exposed via loadbalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingester
  labels: { app: ingester }
spec:
  replicas: 1
  selector:
    matchLabels: { app: ingester }
  template:
    metadata:
      labels: { app: ingester }
    spec:
      containers:
        - name: ingester
          image: ghcr.io/hirashif/crypto-market-pipeline-ingester:latest
          env:
            - { name: KAFKA_BROKERS, value: "kafka:9092" }
            - { name: SYMBOLS, value: "BTC-USD,ETH-USD,SOL-USD" }
            - { name: METRICS_ADDR, value: ":2112" }
          livenessProbe:
            httpGet: { path: /healthz, port: 2112 }
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
            requests: { cpu: "25m", memory: "32Mi" }
            limits: { cpu: "200m", memory: "128Mi" }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  labels: { app: processor }
spec:
  replicas: 1
  selector:
    matchLabels: { app: processor }
  template:
    metadata:
      labels: { app: processor }
    spec:
      containers:
        - name: processor
          image: ghcr.io/hirashif/crypto-market-pipeline-processor:latest
          env:
            - { name: KAFKA_BROKERS, value: "kafka:9092" }
            - { name: REDIS_ADDR, value: "redis:6379" }
            - { name: METRICS_ADDR, value: ":2112" }
          livenessProbe:
            httpGet: { path: /healthz, port: 2112 }
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
            requests: { cpu: "25m", memory: "32Mi" }
            limits: { cpu: "200m", memory: "128Mi" }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels: { app: api }
spec:
  replicas: 1
  selector:
    matchLabels: { app: api }
  template:
    metadata:
      labels: { app: api }
    spec:
      containers:
        - name: api
          image: ghcr.io/hirashif/crypto-market-pipeline-api:latest
          ports:
            - containerPort: 8080
          env:
            - { name: REDIS_ADDR, value: "redis:6379" }
            - { name: HTTP_ADDR, value: ":8080" }
          readinessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
            requests: { cpu: "25m", memory: "32Mi" }
            limits: { cpu: "200m", memory: "128Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: LoadBalancer # azure gives this a public ip on aks
  selector: { app: api }
  ports:
    - port: 80
      targetPort: 8080
